export enum ValidateProfileError {
    INCORRECT_FIRST_LASTNAME = 'INCORRECT_FIRST_LASTNAME',
    INCORRECT_AGE = 'INCORRECT_AGE',
    NO_DATA = 'NO_DATA',
    NO_COUNTRY = 'NO_COUNTRY',
    SERVER_ERROR = 'SERVER_ERROR',
}
