name: Linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    Lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 17.x ]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install modules
              run: npm ci
            - name: Build production project
              run: npm run build:prod
              if: always()
            - name: Lint typescript
              run: npm run lint:ts
              if: always()
            - name: Lint scss
              run: npm run lint:scss
              if: always()
            - name: Unit testing
              run: npm run test:unit
              if: always()

    UI:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Install modules
          run: npm ci
        - name: Storybook build
          run: npm run build-storybook
        - name: Screenshots testing Chromatic
          uses: chromaui/action@latest
          with:
            projectToken: chpt_025e1e413343d56

